name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v11
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: git submodule update --init --recursive
    - run: nix-build release.nix
    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: result/bin/nelder-mead
