name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache install Nix packages
      uses: nix-actions/cache-install@v1.0.6
      with:
        key: nix-${{ hashFiles('mypackages.nix') }}
        nix_file: 'mypackages.nix'
    - run: git submodule update --init --recursive
    - run: nix-build release.nix
    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: result/bin/nelder-mead
