name: "Build documentation"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install texlive-base texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended doxygen
    - run: sudo pip3 install jinja2 Pygments
    - run: cd docs && ./m.css/documentation/doxygen.py conf.py
    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: docs/_build/
